Refactor Coq Batch 2, Batch 4, Batch 6, Batch 8, Batch 9
trishullab/PutnamBench pull request #131
Opened 2024-07-06 05:01 UTC by michelled01

2024-07-08 14:54 UTC, GeorgeTsoukalas requested changes
Assignment.v seems to be in a format not reflecting the corresponding Lean version (one big statement to prove, no hypotheses)

2024-07-09 03:25 UTC, michelled01 commented
Fixed a merge conflict and addressed suggestions. Ready for merge

2024-07-09 03:27 UTC, michelled01 commented
Nvm there's still one thing I need to do

2024-07-09 13:37 UTC, GeorgeTsoukalas approved these changes

2024-07-09 13:37 UTC, merged