More minor fixes to informal problem solutions.
trishullab/PutnamBench pull request #223
Opened 2024-10-04 17:18 UTC by elkhrt

2024-10-05 17:07 UTC, GeorgeTsoukalas requested changes
Thanks for pointing out these issues! In general we've tried to keep the format to be "Show that a/the solution is _" so that this could be easily used for someone trying to do informal proof generation conditioned on the answer. Might you be willing to modify 2015_a2 and 2019_b6 to generally reflect this format? I can also specify this in the README

2024-10-05 17:37 UTC, elkhrt commented
FWIW, it would be helpful for me to have a simple list of possible answers for the problems which are in the form of a question. I can easily do that transformation locally of course.

2024-10-05 20:59 UTC, GeorgeTsoukalas commented
Here is a set of examples (so long as `informal_solution` contains an imperative sentence which is reasonable in context I think the exact wording can be up to interpretation):

1. Problem does not require exhibiting a solution; Convention: "None."
2. Find all x such that P x; Convention: "Show that the set of solutions is _"/"Show that the statement is true for all x in _"
3. Find an x such that P x; Convention: if the Lean formalization exhibits only a single x (though multiple were possible), for better alignment then "Show that a solution is _" else "Show solutions can be taken from _"
4. Is the statement P true? Convention; "Show that the statement is {true/false}" or "Show that 'P is true'"
5. Find the minimum value of x such that P x; Convention: "Show that the minimum value is _"

Again this is mostly up to interpretation and based on the exact stating of the question. The only example I might amend would be "Every n \geq 1" -> "Show that the statement is true for all n \geq 1" to fit an imperative form.

It is a bit regrettable that we let some issues slip through on the informal end, thanks for looking for them! I'll also do a pass myself to see if there's any further declarative informal_solutions.

2024-10-05 21:12 UTC, elkhrt commented
Done.

2024-10-06 00:18 UTC, GeorgeTsoukalas commented
Looks like the check failed. Think there's an escaping issue in the latest "Rephrasing" commit

2024-10-07 11:44 UTC, eric-wieser commented
> 1. Problem does not require exhibiting a solution; Convention: "None."

Maybe using the JSON `null` would be more appropriate for these, to avoid ambiguity with "how many such functions exist? answer: none"

2024-10-07 11:46 UTC, eric-wieser commented on informal/putnam.json
> +        "informal_solution": "Show that the statement is true for every n \geq 1",
```suggestion
        "informal_solution": "Show that the statement is true for every \\(n \\geq 1\\)",
```

2024-10-07 12:29 UTC, elkhrt commented
> > 1. Problem does not require exhibiting a solution; Convention: "None."
> 
> Maybe using the JSON `null` would be more appropriate than `"None."` for these, to avoid ambiguity with "how many such functions exist? answer: none"

Or just omitting it entirely.

2024-10-07 15:03 UTC, GeorgeTsoukalas commented
Ideally the imperative-style of `informal_solution` when it exists should preclude confusion. Anyways, I think omitting it entirely seems reasonable, writing "None." was a very early design choice in this project. I'll merge this and the omission can be the subject of a different PR. Thank you for the contribution, Edward!

2024-10-07 15:04 UTC, merged